version: "3"

volumes:
  prometheus_data: {}
  grafana_data: {}

services:

  prometheus-gmail-exporter:
    build:
      context: .
    container_name: prometheus-gmail-exporter
    volumes:
      - ./config:/app
    ports:
      - "2112:2112"
    restart: always

  prometheus:
    image: prom/prometheus:v2.31.1
    volumes:
    - ./prometheus:/etc/prometheus
    - prometheus_data:/prometheus
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    - '--storage.tsdb.retention.time=365d'
    - '--web.console.libraries=/usr/share/prometheus/console_libraries'
    - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
    - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana

